### ISSUE TITLE
Non-coder: Help would be appreciated

### ISSUE THREAD

**Issue by teduez** [billchaison/asus-router-decoder#1]
Well, this isn't really an 'issue.' I'm just not a coder but really need to decode my asus ac3100 cfg file because it keeps saying my password is incorrect. Any instructions on how to save the file and run this in the mac os terminal window? I've tried and when I run the file here's what I get:

./asus-router-decoder.sh
./asus-router-decoder.sh: line 1: {rtf1ansiansicpg1252cocoartf2708: command not found
./asus-router-decoder.sh: line 2: syntax error near unexpected token `}'
./asus-router-decoder.sh: line 2: `\cocoatextscaling0\cocoaplatform0{\fonttbl\f0\fswiss\fcharset0 Helvetica;}'

🤦‍♀️🤷‍♀️

**Comment by billchaison** [comment]
You will probably need to run the script on a Linux OS instead of MacOS terminal.  There are some references in the script like "stat" and conditional checks that may be incorrect for integer comparisons on MacOS.  On the repo page where the script appears, mouse over the script block and click on the copy button that appears in the corner, then paste that text into the shell script on Linux.  You will need to "chmod +x" the script or call it as an argument with bash.
